name: Push - Single Build & Test (on push)

# workflow is for a branch push only and ignores main.
# push to main (which is also pull request merge) has a more elaborate workflow to run
# github repo is configured with branch protection on main.
on: 
  push:
    branches-ignore:
      - 'main'
      # any branch with a name ending in -no-action will not trigger this workflow.
      - '*-no-action'

  workflow_dispatch:
    inputs: 
      node:
        required: false
        description: 'A node version (e.g 10.16.0)'
        default: '16'

jobs:
  build-single-test:
    name: Build Single Test
    runs-on: ubuntu-latest # environment job will run in

    env:
      SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY }}
      SW_APM_COLLECTOR: ${{ secrets.SW_APM_COLLECTOR }}
      SW_TEST_PROD_SERVICE_KEY: ${{ secrets.SW_TEST_PROD_SERVICE_KEY }}

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Setup Node ${{ github.event.inputs.node || '16' }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ github.event.inputs.node || '16' }}

      - name: Show Environment Info
        run: |
          printenv
          node --version
          npm --version 
          cat /etc/os-release

      # must install specific dependencies before a build
      # can't call npm install. doing so may fallback-to-build if package has yet to be published (double build)
      # use npm workaround specifying a package name to bypass install script in package.json
      - name: NPM Install dependencies
        run: npm install linux-os-info --unsafe-perm

      # runs: node setup-liboboe.js && node-pre-gyp install --build-from-source
      - name: NPM Install with Rebuild from source
        run: npm run rebuild

      - name: Run tests
        run: npm test
